let SelectData = {

	data: ['Abogados', 
		'Administracion', 
		'Arquitectos', 
		'ArtesDiseno', 
		'Camareros', 
		'Cocineros', 
		'Comerciales', 
		'Construccion', 
		'Consultores', 
		'Contables', 
		'ControlCalidad', 
		'Directivos', 
		'Educacion', 
		'Finanzas',
		'Gerentes',
		'Informaticos',
		'Ingenieros',
		'Investigadores',
		'Marketing',
		'Mensajeros',
		'Periodistas',
		'Publicidad',
		'RecursosHumanos',
		'Sanidad',
		'ServicioDomestico',
		'ServiciosSociales',
		'Traductores',
		'Transportistas',
		'Turismo',
		'Porteros',
		'Vigilantes',
		'Otros',]
}


let SelectTexto = {

	texto: ['Abogados', 
	   	  'Administración', 
		  'Arquitectos', 
		  'Artes y Diseño', 
		  'Camareros', 
		  'Cocineros', 
		  'Comerciales', 
		  'Construcción', 
		  'Consultores', 
		  'Contables', 
		  'Control de calidad', 
		  'Directivos', 
		  'Educación', 
		  'Finanzas',
		  'Gerentes',
		  'Informáticos',
		  'Ingenieros',
		  'Investigadores',
		  'Márketing',
		  'Mensajeros',
		  'Periodistas',
		  'Publicidad',
		  'Recursos Humanos',
		  'Sanidad',
		  'Servicio Domestico',
		  'Servicios Sociales',
		  'Traductores',
		  'Transportistas',
		  'Turismo',
		  'Porteros',
		  'Vigilantes',
		  'Otros',]
}